# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

# Model arguments
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: _
  checkpoint_files: [hf_model_0001_2.pt, hf_model_0002_2.pt, hf_model_0003_2.pt, hf_model_0004_2.pt]
  output_dir: _
  model_type: LLAMA3

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: _

prompt:
  user: _
  
# # Generation arguments; defaults taken from gpt-fast
max_new_tokens: 300
temperature: 0.1 # 0.8 and 0.6 are popular values to try
top_k: 30

enable_kv_cache: true

quantizer:
